### PR TITLE
1D analysis

### LINKED ISSUE #189: 1D profiles of images and visibility models
**Is your feature request related to a problem or opportunity? Please describe.**
For general analysis of MPoL results, and especially for comparison to `frank`, it would be useful to have routines to extract a 1D (radial) profile from an MPoL image and visibility model. 

**Describe the solution you'd like**
A new program with two functions: 
- extracting a radial profile from an image (including deprojection) 
- extracting a radial profile from a visibility model (including flux rescaling for optically thick sources)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**How might you be able to help with the development of this feature?**
I will add the new program and tests with a mock dataset.

### PR DESCRIPTION
**Pull request by jeffjennings**
Adds utilities to obtain the 1d (radial) representation of:
    - an image (such as that obtained from an MPoL model), `onedim.radialI`
    - a visibility distribution (such as that obtained from an MPoL model), `onedim.radialV`

`radialI` expects an image array rather than an ImageCube, and `radialV` expects a set of 2D visibility amplitudes rather than a FourierCube. I did this to make the routines immediately accessible for generic numpy arrays, so a bit of preprocessing from cubes is required (if I'd done the converse, a bit of processing for numpy arrays would be required, and I thought it best to keep the functions in this slightly more general design).

*Note:*
Adds `frank` as an `EXTRA_REQUIRES` : `tests` and `analysis` dependency. 

Todo: 
- [x] radial image space function `radialI`
- [x] radial visibility function `radialV` (account for optically thick vs thin)
- [x] add tests

Closes #189 

This should only be reviewed and merged after #195 is resolved, as that branch was pulled into this one.

### CODE REVIEW

**Comment by jeffjennings** [comment]
`test_radialI` diagnostic plot, showing the correct recovery of a 1d brightness profile from a projected 2d image: 
test_radialI

`test_radialV` diagnostic plot, showing the correct recovery of a 1d visibility profile from a projected visibility distribution:
test_radialV

**Comment by jeffjennings** [comment]
This should only be reviewed and merged after #195 is resolved, as that branch was pulled into this one.

**Comment by jeffjennings** [comment]
> This is excellent!
> 
> > radialI expects an image array rather than an ImageCube, and radialV expects a set of 2D visibility amplitudes rather than a FourierCube. I did this to make the routines immediately accessible for generic numpy arrays, so a bit of preprocessing from cubes is required (if I'd done the converse, a bit of processing for numpy arrays would be required, and I thought it best to keep the functions in this slightly more general design).
> 
> I would be in favor of doing the converse, but we should have a broader discussion about core objects in the codebase. My reasoning is that the `ImageCube` is a well-defined object of MPoL with [conventions](https://mpol-dev.github.io/MPoL/units-and-conventions.html#image-cube-packing-for-ffts) on how it should be packed and its dimensionality, whereas a numpy image array is just a numpy array. So to have this work correctly on numpy arrays, we then need to impose conventions on correct intake of numpy arrays, which might give users another potentially confusing object to deal with.
> 
> What types of data do you envision these routines to work on? I would think the `radialI` and `radialV` would be most useful directly applied to `ImageCube`s and `FourierCube`s produced directly from an RML optimization loop, but maybe you have other use cases in mind.

That makes sense, I'm happy to change it to require less/no pre-processing for mpol model inputs. I was thinking of images generated by external software, like .fits obs or images from simulations. But it's equally easy to stuff those into cubes.  `['1'] * 6` sort of thing.

**Comment by jeffjennings** [comment]
@iancze I updated `radialI` (`radialV`) to take in an `ImageCube` (`FourierCube`) - ready for review.

**Review by iancze — APPROVED** [review]
Thanks, this looks great!

**Pull request merged**
