### PR TITLE
removed persistent buffer and fixed some typos.

### LINKED ISSUE #143: Some docs tutorial cells broken
**Describe the bug**
Recent changes to some code routines broke individual jupyter cells in some of the docs tutorials - just a few cases: 

https://mpol-dev.github.io/MPoL/ci-tutorials/fakedata.html

https://mpol-dev.github.io/MPoL/ci-tutorials/initializedirtyimage.html

https://mpol-dev.github.io/MPoL/ci-tutorials/gridder.html

**Additional context**
The `docs_build` workflow should catch this, so either it didn't run on the relevant merge commits, or it's not catching errors in the tutorial notebook cells.

### PR DESCRIPTION
**Pull request by iancze**
Closes #143

### CODE REVIEW

**Comment by iancze** [comment]
Something still seems to be wacky with the GitHub actions. The build errored on "docs test #62" but if you look at the error log it's a result from a stale tutorial. IDK if this has to do with the MystNB cache or the GitHub actions cache or both.

**Review by kadri-nizam — APPROVED** [review]
Thanks for fixing the typo in images_test! I suspect it's the cache. Might need to update the `conf.py` file as it's currently set to cache mode.
https://github.com/MPoL-dev/MPoL/blob/b6d9b2460a447fcc536433b28a0a1fcc46280644/docs/conf.py#L93

**Comment by kadri-nizam** [comment]
I think I understand now. The tests were failing on the `pull_request_target` action because
> This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does.
So, actions run using `pull_request_target` will run tests based on the unchanged codes in the repository. I'll go ahead and merge this since tests run on the head has no errors.

**Comment by iancze** [comment]
Thanks for tracking this down! If the `pull_request_target` action is just running on the `main` branch, is there any utility to it then, at least in our workflow? @jeffjennings

**Comment by jeffjennings** [comment]
I think pull_request_target is needed to run tests on a PR from a fork
(just pull_request wasn’t running tests on the last forked PR), but maybe
there’s another workaround.

**Comment by iancze** [comment]
Thanks, that makes sense!

**Pull request merged**
